export const keywordsLayoutArray = {
  ar: [
    "amro97 Team",
    "فريق amro97",
    "تصميم مواقع",
    "تصميم مواقع إلكترونية",
    "تطوير مواقع",
    "تطوير مواقع إلكترونية",
    "برمجة مواقع",
    "إنشاء موقع إلكتروني",
    "إنشاء مواقع",
    "بناء مواقع",
    "مطور مواقع",
    "مبرمج مواقع",
    "شركة تصميم مواقع",
    "خدمات تصميم المواقع",
    "خدمات تطوير المواقع",
    "تصميم متجر إلكتروني",
    "برمجة متجر إلكتروني",
    "تطوير تطبيقات الويب",
    "مواقع احترافية",
    "تصميم مواقع للشركات",
    "تصميم مواقع للأعمال",
    "Next.js",
    "React",
    "TypeScript",
  ],

  en: [
    "amro97 Team",
    "amro97 web development",
    "web development",
    "website development",
    "website design",
    "web design",
    "website developer",
    "web developer",
    "professional website development",
    "custom website development",
    "business website development",
    "company website development",
    "web development services",
    "website design services",
    "build a website",
    "create a website",
    "ecommerce website development",
    "web application development",
    "full stack web development",
    "Next.js development",
    "React development",
    "TypeScript development",
    "Next.js developer",
    "React developer",
  ],
};