import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import { Navbar } from "../../components/Navbar";
import { Footer } from "../../components/Footer";
import { PopupWidget } from "../../components/PopupWidget";
import AppProvider from "../../components/AppContext";
import { AppContext } from "./context/AppContext";

import AppContextProvider from "./context/AppContext";
import { Providers } from "./provider";
import { getLocale } from "next-intl/server";

import styles from "./layout.module.css"; 


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web Dev Service",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  console.log(locale);
  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <head>
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      ></link>

      <style>
        @import
        url('https://fonts.googleapis.com/css2?family=Alexandria:wght@100..900&family=Cairo:wght@200..1000&family=Readex+Pro:wght@160..700&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap');
      </style>

      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2595619116828936"
     crossorigin="anonymous"></script>
      </head>

      <body
        className={`${inter.className} max-w-full mx-auto sm:max-w-[95%] md:max-w-[90%] xl:max-w-[85%] relative 
        overflow-x-hidden
         ${locale === 'ar' ? styles.arabic : styles.english}`}
      >
        <NextIntlClientProvider messages={messages}>
          <AppProvider>
            <AppContextProvider>
              <Navbar />

              <Providers>
                <div>{children}</div>
              </Providers>

              <Footer />
              <PopupWidget />
            </AppContextProvider>
          </AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
