import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import { NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import { Navbar } from "../../components/Navbar";
import { Footer } from "../../components/Footer";
import { PopupWidget } from "../../components/PopupWidget";
import AppProvider from "../../components/AppContext";
import { AppContext } from "./context/AppContext";

import AppContextProvider from "./context/AppContext";
import { Providers } from "./provider";
import { getLocale } from "next-intl/server";

import styles from "./layout.module.css";

import { Analytics } from "@vercel/analytics/next";
import { description, title } from "@/constants/title";
import { keywordsLayoutArray } from "@/constants/keyowrdsLayoutArray";
import AdsBar from "../components/AdsBar";

// import { AdsBar } from "@amro97/next-ads";

const inter = Inter({ subsets: ["latin"] });

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  // const t = await getDictionary(params.locale); // returns translation object

  // const locale = params.locale;

  const { locale } = await params;

  return {
    metadataBase: new URL("https://www.wds-oman.com"),
    // title: params.locale === "ar" ? "نبذة عنا" : "About Us - Work Remotely",
    // title: {
    //   default: locale === "ar" ? "عمل عن بعد" : "Work Remotely",
    //   template: locale === "ar" ? "%s - عمل عن بعد" : "%s - Work Remotely",
    // },

    title: {
      default: locale === "ar" ? title.ar : title.en,
      template: locale === "ar" ? `%s - ${title.ar}` : `%s - ${title.en}`,
    },

    // description:
    //   locale === "ar"
    //     ? "هذه منصة تتيح لك البحث عن فرص عمل عن بعد وتتيح لأصحاب الأعمال عرض الوظائف التي لديهم"
    //     : "This is a platform that allows you to search for remote job opportunities and enables employers to post the jobs they have",

    description: locale === "ar" ? description.ar : description.en,

    twitter: {
      card: "summary_large_image",
    },

    icons: {
      icon: "/favicon.ico",
      shortcut: "/favicon.ico",
      apple: "/apple-touch-icon.png",
    },

    alternates: {
      canonical: `https://www.wds-oman.com/${locale}`,
      languages: {
        en: "https://www.wds-oman.com/en",
        ar: "https://www.wds-oman.com/ar",
      },
    },

    keywords: locale === "ar" ? keywordsLayoutArray.ar : keywordsLayoutArray.en,
  };
}


// export const metadata: Metadata = {
//   // title: "Web Dev Service",
//   title: {
//     default: "Web Dev Service",
//     template: "%s - Web Dev Service",
//   },
//   description: "Generated by create next app",
//   twitter: {
//     card: "summary_large_image",
//   },
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const homePage = await getTranslations({ locale, namespace: "HomePage" });

  const locale = await getLocale();

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages({ locale });

  console.log(locale);
  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        ></link>

        <style>
          @import
          url(&apos;https://fonts.googleapis.com/css2?family=Alexandria:wght@100..900&family=Cairo:wght@200..1000&family=Readex+Pro:wght@160..700&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap&apos;);
        </style>

        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2595619116828936"
          crossOrigin="anonymous"
        ></script>

        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4591435109060126"
          crossOrigin="anonymous"
        ></script>
      </head>

      <body
        className={`${inter.className} max-w-full mx-auto sm:max-w-[95%] md:max-w-[90%] xl:max-w-[85%] relative 
        overflow-x-hidden
         ${locale === "ar" ? styles.arabic : styles.english}`}
      >
        <NextIntlClientProvider messages={messages}>
          <AppProvider>
            <AppContextProvider>
              <Navbar />

              <AdsBar
                  // title={homePage("Advertising and Promotion")}
                  // whatsapp={homePage("Whatsapp")}
                  // whatsappNumber={`+96879335801`}
                  // email={homePage("Email")}
                  // emailAdress={`admin@wds-oman.com`}
                />

              <Providers>
                {children}
                <Analytics />
              </Providers>

              <Footer />
              <PopupWidget />
            </AppContextProvider>
          </AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
